from tkinter import *
root=Tk()
def getvals():
    print(f"YOUR NAME IS {namevalue.get()}")
    print(f"YOUR PHONE IS {phonevalue.get()}")
    print(f"YOUR Gender IS {gendervalue.get()}")
    print(f"YOUR EMERGENCY CONTACT IS {emergencyvalue.get()}")
    print(f"YOUR PAYMENT MODE IS {paymentvalue.get()}")
    print(foodservicevalue.get())
    with open("records.txt","w") as f:
        f.write(f"{namevalue.get(),phonevalue.get(),gendervalue.get(),emergencyvalue.get(),paymentvalue.get(),foodservicevalue.get()}\n")

root.geometry("666x500")
Label(root,text="Welcome to Prajwal Travellers",font="comicsansms 13 bold").grid(row=0,column=3)
name=Label(root,text="Name")
phone=Label(root,text="Phone")
gender=Label(root,text="gender")
emergency=Label(root,text="Emergeny Contact")
payment=Label(root,text="Payment Mode")
name.grid(row=1,column=2)
phone.grid(row=2,column=2)
gender.grid(row=3,column=2)
emergency.grid(row=4,column=2)
payment.grid(row=5,column=2)
namevalue=StringVar()
phonevalue=StringVar()
gendervalue=StringVar()
emergencyvalue=StringVar()
paymentvalue=StringVar()
foodservicevalue=IntVar()
nameentry=Entry(root,textvariable=namevalue)
phoneentry=Entry(root,textvariable=phonevalue)
genderentry=Entry(root,textvariable=gendervalue)
emergencyentry=Entry(root,textvariable=emergencyvalue)
paymententry=Entry(root,textvariable=paymentvalue)
foodserviceentry=Entry(root,textvariable=foodservicevalue)
nameentry.grid(row=1,column=3)
phoneentry.grid(row=2,column=3)
genderentry.grid(row=3,column=3)
emergencyentry.grid(row=4,column=3)
paymententry.grid(row=5,column=3)

foodservice=Checkbutton(text="Want to prebook your meals ?",variable=foodservicevalue)
foodservice.grid(row=6,column=3)
Button(text="Submit",command=getvals).grid(row=7,column=3)

root.mainloop()
